version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env  # Load environment variables from .env file

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookly_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d bookly_db"]
      interval: 10s
      retries: 5
      
  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
